### ISSUE TITLE
Incorrect onnxruntime-gpu version fixed in requirements.txt

### ISSUE THREAD

**Issue by nikomilon** [stephansturges/WALDO#11]
The current `requirements.txt` file references an onnxruntime_gpu version 1.15.1. However, there is no version 1.15.1 available. See the [releases](https://pypi.org/project/onnxruntime-gpu/) on the pypi page.

Running the `pip install` command results in an error:
`ERROR: Could not find a version that satisfies the requirement onnxruntime_gpu==1.15.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime_gpu==1.15.1`

The version could be fixed to onnxruntime-gpu==1.15.0.

**Comment by stephansturges** [comment]
fix by @kevinlacaille
