### ISSUE TITLE
ERROR TO EXECUTE

### ISSUE THREAD

**Issue by hectorgie** [stephansturges/WALDO#12]
I recently downloaded the full version of the project. However, I have encountered difficulties trying to run it and obtain the resulting video. So far, I have not received any error messages.

Upon consulting the provided "readme" file, it is indicated that to make the project work correctly, I should run the "run_local_onnx_on_videos.py" file using Python 3. However, in the version I downloaded, I only find a file named "run_local_network_on_videos_onnxruntime."

When I tried to rename this file and run it as indicated, I got the following result:

[https://drive.google.com/drive/folders/13gB6gAa2ABdLAG-p1BNtpSuCPBVDp6Ok?usp=sharing](url)

I am looking forward to your additional instructions to successfully proceed with running this project. If possible, please provide me with more details or any necessary files to achieve this.

I am at your disposal for any further questions. Thank you for your attention!

**Comment by FrancisCB92** [comment]
The downloaded WinRAR has its own updated Readme.
