### ISSUE TITLE
Fine tuning pretrained model is not working

### ISSUE THREAD

**Issue by ralphSmith300000** [stephansturges/WALDO#17]
I am trying to fine tune the available .pt files so i can train them on custom dataset, but when i am trying to load those models i am getting the following error:
**ModuleNotFoundError: No module named 'models'**
I am using the following code to load the model:
`model = torch.load(model_path)`
The solutions i have tried: ( didn't work)
- Trying to load the module 'models' manually by: `import models` , but this gives `ModuleNotFoundError` , and then i try to install it via pip, but it seems that the modules need some kind of installations that i didn't find how to do it.
- in : [pypi-models](https://pypi.org/project/models/) , there doesn't seem any documentation that is reliable to this module, and also it seems that it is an old module that has no update from 2010.

Can you please give an explanation of how to fine tune available models, and how to train them on custom dataset?

Thank you.

**Comment by stephansturges** [comment]
these are yolov7 models, load them with pytorch following the docs in https://github.com/WongKinYiu/yolov7
