### ISSUE TITLE
Readme update for python scripts

### ISSUE THREAD

**Issue by patrickpoirier51** [stephansturges/WALDO#4]
Hello Stephen
Thanks for  making public this amazing work 

It seems that the readme needs some updating as the scripts have changed names
run_local_network_on_videos_onnxruntime.py
local_network_on_images_onnxruntime.py  

And the script need the --model argument now, could you make a working example for the playground demo ?

Best regards

**Comment by stephansturges** [comment]
Thanks the Readme here has been updated and I'm going to include the update in the next release of the .zip too !
