### ISSUE TITLE
can you help me to solve the below error?

### ISSUE THREAD

**Issue by ThanosUTH** [stephansturges/WALDO#9]
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 2 Got: 960 Expected: 736
 index: 3 Got: 960 Expected: 1088
 Please fix either the inputs or the model.

**Comment by stephansturges** [comment]
running the example code on images?

I think this is the same as https://github.com/stephansturges/WALDO/issues/8

For now take the model shape detection code from the video processing boilerplate, will fix ASAP!
